name: CD

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/ai-article-summarizer-frontend:latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
          provenance: false
          allow: |
            network.host
          outputs: type=image,name=ghcr.io/${{ github.repository_owner }}/ai-article-summarizer-frontend:latest,push=true
